name: CI (scheduled)
on:
  schedule:
  - cron: * 14 * * 0 # Every day 2PM UTC = Monday 12AM AEST
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['8.2', '8.3', '8.4','8.5']
    name: PHP ${{ matrix.php }}
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: mbstring
        coverage: pcov
    - name: Check PHP version
      run: php -v
    - name: Install dependencies
      run: make vendor
    - name: Make
      if: ${{ startsWith(matrix.php, '8.') }}
      run: make ci
    - name: Make
      if: ${{ startsWith(matrix.php, '8.') }}
      run: make artifacts/coverage/phpunit/clover.xml
    - name: Publish coverage
      if: success()
      uses: codecov/codecov-action@v2
